# Generated by Django 3.1.4 on 2020-12-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveBigIntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='rotationchart',
            name='img',
            field=models.ImageField(upload_to='rotation_chart/%Y/%m/%d/', verbose_name='轮播图图片'),
        ),
        migrations.AlterField(
            model_name='rotationchart',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否是activity'),
        ),
        migrations.AlterField(
            model_name='rotationchart',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
